use crate::constants::macros::define_consts;

define_consts! {
    /// 版权信息
    GENERATE_COPYRIGHT: &str = r#" /*
       ___        ___         ___     
      /  /\      /  /\       /  /\    
     /  /:/     /  /::\     /  /:/    
    /  /:/     /  /:/\:\   /  /:/     
   /  /:/     /  /:/~/:/  /  /:/  ___ 
  /  /::\    /__/:/ /:/  /__/:/  /  /\
 /  /:/\:\   \  \:\/:/   \  \:\ /  /:/
/__/:/  \:\   \  \::/     \  \:\  /:/ 
\__\/ \  \:\   \  \:\      \  \:\/:/  
       \  \:\   \  \:\      \  \::/   
        \__\/    \__\/       \__\/    
Copyright GVSDS Team
Actor TermiNexus 
Generated by TransPyC
*/"#;
}
