use crate::constants::macros::define_map;

define_map! {
    TYPE_MAP,
    "CInt" => "int",
    "CChar" => "char",
    "CShort" => "short",
    "CLong" => "long",
    "CFloat" => "float",
    "CDouble" => "double",
    "CVoid" => "void",
    "CUnsigned" => "unsigned",
    "CUnsignedChar" => "unsigned char",
    "CUnsignedInt" => "unsigned int",
    "CUnsignedShort" => "unsigned short",
    "CUnsignedLong" => "unsigned long",
    "CSignedChar" => "signed char",
    "CSizeT" => "size_t",
    "CInt8T" => "int8_t",
    "CInt16T" => "int16_t",
    "CInt32T" => "int32_t",
    "CInt64T" => "int64_t",
    "CUInt8T" => "uint8_t",
    "CUInt16T" => "uint16_t",
    "CUInt32T" => "uint32_t",
    "CUInt64T" => "uint64_t",
    "CIntPtrT" => "intptr_t",
    "CUIntPtrT" => "uintptr_t",
    "CPtrDiffT" => "ptrdiff_t",
    "CWCharT" => "wchar_t",
    "CChar16T" => "char16_t",
    "CChar32T" => "char32_t",
    "CBool" => "bool",
    "CComplex" => "_Complex",
    "CImaginary" => "_Imaginary",
    "CPtr" => "*",
}
